server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # Chỉ cần giữ lại cấu hình này để React Router không bị lỗi 404 khi F5 trang
  location / {
    try_files $uri $uri/ /index.html;
  }
}